import pygame

SCENE_REFOCUS = pygame.event.custom_type()
NEW_GAME = pygame.event.custom_type()
CONTINUE = pygame.event.custom_type()
CONTROLS = pygame.event.custom_type()
CREDITS = pygame.event.custom_type()
BACK = pygame.event.custom_type()
PAUSE_CONTINUE = pygame.event.custom_type()
PAUSE_SAVE_AND_QUIT = pygame.event.custom_type()
PAUSE_QUIT_TO_MENU = pygame.event.custom_type()
EQUIP_QUIT = pygame.event.custom_type()
EQUIP_SAVE_AND_START = pygame.event.custom_type()
EQUIP_BUY_CLOUD_SLEEVES = pygame.event.custom_type()
EQUIP_BUY_WINGS = pygame.event.custom_type()
EQUIP_BUY_JET_BOOTS = pygame.event.custom_type()
EQUIP_BUY_MORE_FUEL = pygame.event.custom_type()
QUIT = pygame.QUIT
LOAD = pygame.event.custom_type()
VICTORY = pygame.event.custom_type()
